### ISSUE TITLE
Partially breaking the ACP plugin table view

### ISSUE THREAD

**Issue by sicut** [WildcardSearch/MentionMe#138] opened 2017-03-05 03:46 UTC
Hey,
thanks for the great plugin!

After upgrading our board from 1.8.5 to 1.8.10 we encountered a lot of weird problems with this plugin.
Just fyi, since that is fixed now: The autocomplete function added a permanent empty avatar and some more empty lines below the Quick Reply field. A temporary workaround was to deactivate that feature.
A full fix was not just to deactivate and reactivate the plugin, but to completely reinstall it (same version btw).

But we couldn't fix one small (!) problem: The last 2 columns in the ACP plugin section are being omitted right after MentionMe until the end of the table. Those columns are: "Delete" & "Reimport from MyBB Mods Site" in the "Controls" part of "Active Plugins". 
Weirdly enough that also happens if deactivated - just with the "Inactive Plugins" table then.
When we uninstall it, everything is being shown there normally again.

![screenie](https://cloud.githubusercontent.com/assets/15329246/23584299/9deeaffe-015d-11e7-82ca-46a32eb23f7b.JPG)

**Comment by WildcardSearch** [comment] 2017-03-05 13:35
What plugin are you using to add those extra columns?

**Comment by sicut** [comment] 2017-03-06 02:39
Hey,
~~nothing that I know of, isnt that a standard feature?~~
lol, sorry, since we have three forums and those columns have been there since forever, I totally took them for granted.
It's the [Plugin Uploader Plugin](https://github.com/MattRogowski/Plugin-Uploader). It creates those additional columns for deleting or reimporting/updating a plugin.

**Comment by WildcardSearch** [comment] 2017-03-07 00:59
Okay, that gives me something to go on. I'll install Plugin Uploader on one of my test boards and see if I can locate the problem. I'll @sicut mention you when I have a chance to check it out.

Sorry you are having problems.

**Comment by sicut** [comment] 2017-03-07 23:17
Np, your plugin is greatly loved by our users and that "bug" is extremely minor!
Thanks again for your work!

**Comment by WildcardSearch** [comment] 2017-03-08 01:10
@sicut having had a chance to check things out, I can see the that the issue is with the way Plugin Uploader adds the extra columns in ACP -> Configuration -> Plugins

It is using JavaScript to append the columns and the selectors used target tables. All of my plugins use tables within the plugin information and, as I discovered in testing, all break the display when used with Plugin Uploader. At least that is my take on it. Perhaps @MattRogowski can shed some more light on the subject...

**Comment by WildcardSearch** [comment] 2017-03-25 21:41
@sicut, I haven't heard back from you. Were you ever able to get a solution?

**Comment by Cu8eeeR** [comment] 2017-03-26 09:29
I had same issue on MyBB 1.6 (MentionMe + Plugin Uploader from Matt). However now on MyBB 1.8 works without any issue

**Comment by sicut** [comment] 2017-03-26 11:12
@WildcardSearch Sorry, no, the problem is still there. We tried some different reactivation sequences, but no luck. Since it doesnt seem to happen for everyone (eg @Cu8eeeR ), it could be connected to something else as well.
But it is such a tiny minor issue, everything else is still working flawlessly :)

**Comment by WildcardSearch** [comment] 2017-03-26 13:23
It seems to be an incompatibility with one or more other plugins. I'm sorry that you are having problems.

**Comment by WildcardSearch** [comment] 2017-09-12 21:13
@sicut I'm going to close this as it is really an error with @MattRogowski 's plugin.

**Closed by WildcardSearch** 2017-09-12 21:13 UTC
